apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: example
  POSTGRES_URL: postgresql://postgres:example@postgres:5432/postgres
